module.exports = [
  {
    title: '第 1 部分 树的基本问题',
    icon: 'book',
    children: [
      '/tree/solutions/0094-binary-tree-inorder-traversal.md',
      '/tree/solutions/0100-same-tree.md',
      '/tree/solutions/0101-symmetric-tree.md',
      '/tree/solutions/0102-binary-tree-level-order-traversal.md',
      '/tree/solutions/0103-binary-tree-zigzag-level-order-traversal.md',
      '/tree/solutions/0104-maximum-depth-of-binary-tree.md',
      '/tree/solutions/0105-construct-binary-tree-from-preorder-and-inorder-traversal.md',
      '/tree/solutions/0106-construct-binary-tree-from-inorder-and-postorder-traversal.md',
      '/tree/solutions/0107-binary-tree-level-order-traversal-ii.md',
      '/tree/solutions/0110-balanced-binary-tree.md',
      '/tree/solutions/0111-minimum-depth-of-binary-tree.md',
      '/tree/solutions/0112-path-sum.md',
      '/tree/solutions/0129-sum-root-to-leaf-numbers.md',
      '/tree/solutions/0199-binary-tree-right-side-view.md',
      '/tree/solutions/0222-count-complete-tree-nodes.md',
      '/tree/solutions/0226-invert-binary-tree.md',
      '/tree/solutions/0236-lowest-common-ancestor-of-a-binary-tree.md',
      '/tree/solutions/0257-binary-tree-paths.md',
      '/tree/solutions/0297-serialize-and-deserialize-binary-tree.md',
      '/tree/solutions/0404-sum-of-left-leaves.md',
      '/tree/solutions/0437-path-sum-iii.md',
      '/tree/solutions/0508-most-frequent-subtree-sum.md',
      '/tree/solutions/0572-subtree-of-another-tree.md',
      '/tree/solutions/0863-all-nodes-distance-k-in-binary-tree.md',
      '/tree/solutions/0951-flip-equivalent-binary-trees.md',
      '/tree/solutions/0993-cousins-in-binary-tree.md',
      '/tree/solutions/1079-letter-tile-possibilities.md',
      '/tree/solutions/1080-insufficient-nodes-in-root-to-leaf-paths.md',
    ],
  },
  {
    title: '第 2 部分 二分搜索树',
    icon: 'book',
    children: [
      '/tree/solutions/intro.md',
      '/tree/solutions/1008-construct-binary-search-tree-from-preorder-traversal.md',
      '/tree/solutions/0095-unique-binary-search-trees-ii.md',
      '/tree/solutions/0098-validate-binary-search-tree.md',
      '/tree/solutions/0108-convert-sorted-array-to-binary-search-tree.md',
      '/tree/solutions/0109-convert-sorted-list-to-binary-search-tree.md',
      '/tree/solutions/0220-contains-duplicate-iii.md',
      '/tree/solutions/0230-kth-smallest-element-in-a-bst.md',
      '/tree/solutions/0235-lowest-common-ancestor-of-a-binary-search-tree.md',
      '/tree/solutions/0449-serialize-and-deserialize-bst.md',
      '/tree/solutions/0450-delete-node-in-a-bst.md',
      '/tree/solutions/0897-increasing-order-search-tree.md',
    ],
  },
];
